const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('electronAPI', {
  listPorts:   ()                    => ipcRenderer.invoke('list-ports'),
  readBaseId:  (path, baud, proto)   => ipcRenderer.invoke('read-base-id', path, baud, proto),
  detectGateway: (preferredPath)     => ipcRenderer.invoke('detect-gateway', preferredPath),
  learnDeviceId: (path, gatewayType, timeoutMs) => ipcRenderer.invoke('learn-device-id', path, gatewayType, timeoutMs),
  learnFts14emBaseId: (path, gatewayType, timeoutMs) => ipcRenderer.invoke('learn-fts14em-base-id', path, gatewayType, timeoutMs),
  onFts14emLearnProgress: (callback) => { const listener = (_event, progress) => callback(progress); ipcRenderer.on('fts14em-learn-progress', listener); return () => ipcRenderer.removeListener('fts14em-learn-progress', listener); },
  writeSenderIdsToDevices: (payload) => ipcRenderer.invoke('write-sender-ids-to-devices', payload),
  cancelWriteSenderIds: () => ipcRenderer.invoke('cancel-write-sender-ids'),
  onWriteSenderProgress: (callback) => { const listener = (_event, progress) => callback(progress); ipcRenderer.on('write-sender-progress', listener); return () => ipcRenderer.removeListener('write-sender-progress', listener); },
  disconnectGateway: (payload) => ipcRenderer.invoke('disconnect-gateway', payload),
  saveProjectAs: (payload) => ipcRenderer.invoke('save-project-as', payload),
  openProject: () => ipcRenderer.invoke('open-project'),
  saveProject: (payload) => ipcRenderer.invoke('save-project', payload),
  getLanguage: () => ipcRenderer.invoke('get-language'),
  setLanguage: (language) => ipcRenderer.invoke('set-language', language),
  onMenuAction: (callback) => { const listener = (_event, action) => callback(action); ipcRenderer.on('menu-action', listener); return () => ipcRenderer.removeListener('menu-action', listener); },
  openDeviceDatabase: () => ipcRenderer.send('open-device-database'),
  closeDeviceDatabase: () => ipcRenderer.send('close-device-database'),
  loadDeviceDatabase: () => ipcRenderer.invoke('load-device-database'),
  openDeviceDatabaseFile: () => ipcRenderer.invoke('open-device-database-file'),
  saveDeviceDatabaseFile: (content) => ipcRenderer.invoke('save-device-database-file', content),
  saveDeviceDatabase: (database) => ipcRenderer.invoke('save-device-database', database),
  deviceDatabaseSaved: (database) => ipcRenderer.send('device-database-saved', database),
  onDeviceDatabaseChanged: (callback) => { const listener = (_event, database) => callback(database); ipcRenderer.on('device-database-changed', listener); return () => ipcRenderer.removeListener('device-database-changed', listener); },
  onLanguageChanged: (callback) => { const listener = (_event, language) => callback(language); ipcRenderer.on('language-changed', listener); return () => ipcRenderer.removeListener('language-changed', listener); },
  isElectron:  true,
});
